---
# Only update apt cache if older than 1 hour
apt_cache_valid_time: 3600


## Tailscale

# Define these somewhere else, like in your gitignored inventory file
# tailscale_key: ""
# tailscale_tags: [] # Omit "tag:" prefix

# Tailscale up arguments
tailscale_args: "--accept-routes"

# Don't register node as ephermeral
tailscale_oauth_ephemeral: false


## Zram
# Disabled if zram_percent is 0 or less

# Percentage of total memory to allocate to zram
zram_percent: 20

# Compression algorithm to use
zram_algorithm: lzo-rle
