---
# Only set public variables here, private variables should be set in inventory
# or somewhere else that is gitignored
# Private variables are commented out here for reference

# In this playbook, you can override any variable by defining an override_x variable
# for any x variable. For example, to override the variable "test", define "override_test".

# Only update apt cache if older than 1 hour
apt_cache_valid_time: 3600


## Tailscale
# tailscale_key: ""
# tailscale_tags: [] # Omit "tag:" prefix

# Tailscale up arguments
tailscale_args: "--accept-routes"

# Don't register node as ephermeral
tailscale_oauth_ephemeral: false


## Zram
# Disabled if zram_percent is 0 or less

# Percentage of total memory to allocate to zram
zram_percent: 20

# Compression algorithm to use
zram_algorithm: lzo-rle


## CrowdSec
# CrowsSec won't be setup by default, override for public facing servers
# by setting override_setup_crowdsec for specific hosts/groups in inventory
setup_crowdsec: false


## Kopia
# Kopia server, with "https://" prefix:
# kopia_server: "https://backup:51515"
# Fingerprint of kopia server's certificate:
# kopia_fingerprint: ""

# Kopia password, user is always "root"
# kopia_password: ""
# kopia_override_hostname: "" (optional)

# What to backup
kopia_targets:
  - path: "/home"
    # Add .kopiaignore file at the root of the path (optional)
    add_kopiaignore: |
      # Global directories and files
      .cache
      *.tmp
      *.bak
      [Dd]esktop.ini

      # Home directories
      */.gradle
      */.konan
      */.m2
      */.npm
      */.vscode-server
      */.vscode-remote-containers
      */.local/lib
      */.local/share/Trash
      */go
      */snap
  - path: "/etc"
    add_kopiaignore: |
      crowdsec/hub
      crowdsec/patterns
      crowdsec/parsers
      crowdsec/notifications
      *.bak
  - path: "/srv"
    add_kopiaignore: |
      .cache

# Kopia backup schedule in systemd timer format
kopia_schedule: "*-*-* 04:00:00"

# Kopia before and after backup commands (optional)
kopia_before_backup: "echo 'Starting backup'"
kopia_after_backup: "echo 'Backup complete'"
