---
roles:
  - name: artis3n.tailscale
    version: "4.5.0"
  - name: nickjj.docker
    version: "2.5.0"

collections:
  - name: devsec.hardening
    version: "10.1.0"
  - name: hifis.toolkit
    version: "5.0.0"
