---
- name: Install security auditing tools
  ansible.builtin.include_tasks: auditing.yml

- name: Configure Firewall
  ansible.builtin.include_tasks: firewall.yml

- name: Harden system and components
  ansible.builtin.include_tasks: hardening.yml
