---
- name: Install security auditing tools
  ansible.builtin.include_tasks: auditing.yml

- name: Enable automatic security updates
  ansible.builtin.include_tasks: autoupdates.yml

- name: Configure Firewall
  ansible.builtin.include_tasks: firewall.yml

- name: Harden system and components
  ansible.builtin.include_tasks: hardening.yml

- name: Setup CrowdSec
  ansible.builtin.include_tasks: crowdsec.yml
  when: setup_crowdsec | bool
