---
- name: Add Tailscale apt repository
  ansible.builtin.deb822_repository:
    name: Tailscale
    uris: "https://pkgs.tailscale.com/stable/{{ distro }}"
    suites: "{{ suite }}"
    components: main
    signed_by: "https://pkgs.tailscale.com/stable/{{ distro }}/{{ suite }}.noarmor.gpg"
  vars:
    distro: "{{ ansible_distribution | lower }}"
    suite: "{{ ansible_distribution_release | lower }}"
  become: true
  register: tailscale_repo

- name: Install tailscale package
  ansible.builtin.apt:
    update_cache: "{{ tailscale_repo.changed }}"
    pkg:
      - tailscale
    state: present
  become: true
