---
- name: Update packages
  ansible.builtin.apt:
    # cache already updated in prerequisites
    upgrade: "safe"
    autoremove: true
  become: true

- name: Install essential packages
  ansible.builtin.apt:
    pkg:
      - git
      - htop
      - tmux
      - screen
      - 7zip
      - ncdu
      - stow
  become: true
